//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.10 at 11:30:12 AM PDT 
//


package recipe;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}ingredient" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}instructions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prep_time" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cook_time" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "ingredient",
    "instructions"
})
@XmlRootElement(name = "recipe")
public class Recipe {

    @XmlElement(required = true)
    protected String title;
    protected List<Ingredient> ingredient;
    @XmlElement(required = true)
    protected Instructions instructions;
    @XmlAttribute(name = "prep_time", required = true)
    protected String prepTime;
    @XmlAttribute(name = "cook_time", required = true)
    protected String cookTime;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the ingredient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ingredient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIngredient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ingredient }
     * 
     * 
     */
    public List<Ingredient> getIngredient() {
        if (ingredient == null) {
            ingredient = new ArrayList<Ingredient>();
        }
        return this.ingredient;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link Instructions }
     *     
     */
    public Instructions getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instructions }
     *     
     */
    public void setInstructions(Instructions value) {
        this.instructions = value;
    }


    /**
     * Gets the value of the prepTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrepTime() {
        return prepTime;
    }

    /**
     * Sets the value of the prepTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrepTime(String value) {
        this.prepTime = value;
    }

    /**
     * Gets the value of the cookTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookTime() {
        return cookTime;
    }

    /**
     * Sets the value of the cookTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookTime(String value) {
        this.cookTime = value;
    }
    
    @Override
    public String toString() {
        String result = "Recipe: " + title + " " + prepTime +"/" + cookTime;
        for (Ingredient i : ingredient) result += "\n  " + i;
        return result + instructions;
    }
}
